config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Vue de composant
  get "/components", to: 'cities#components', as: :components

  #racine de l'app
  root to: 'cities#home', as: :root

  post '/search', to: 'cities#search', as: :search_city # redirection avec l'id

  get '/explications/:name', to: 'cities#explications', as: :explications # Avec id de la ville

  post '/city/:city_id', to: 'itineraires#search', as: :post_city # Crée l'itinéraire avec l'id de la ville --> redirige avec id itinéraire

  get '/vos-monuments/:id', to: 'itineraires#choice', as: :choice
  # permet d'ajouter avec AJAX un monument à un itinéraire
  post '/vos-monuments/:id/:monument_id', to: 'itineraires#ajout', as: :ajout
  delete '/vos-monuments/delete/:id/:monument_id', to: 'itineraires#delete', as: :delete

  #affichage du recap
  get '/synthese/:id', to: 'itineraires#recap', as: :recap # avec id itinéraire
  #delete avec AJAX d'un monument à un itinéraire
  post '/synthese/:id/:monument_id', to: 'itineraires#supprimer', as: :supprimer

  #affichage de l'itinéraire
  get '/itineraire/:id', to: 'itineraires#show', as: :itinary # avec id itinéraire

  post '/itineraires/:id', to: 'itineraires#metrics', as: :metrics # Enregistrement des metrics de l'itinéraire

  get '/vos-itineraires', to: 'itineraires#display', as: :display #affichage des itinéraires précedent de l'utilisateur
#page mes itinéraires (par villes)

  get '/geocoder', to: 'itineraires#geocoder'

  post '/itineraire/point-depart/:id', to: 'itineraires#point_de_depart'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <%= notice %>

    <script>
      var x = document.querySelector(".alert");
      setTimeout(function(){ x.classList.toggle("show"); }, 1000);
      setTimeout(function(){ x.classList.toggle("show"); }, 5000);
    </script>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <%= alert %>

    <script>
      var x = document.querySelector(".alert");
      setTimeout(function(){ x.classList.toggle("show"); }, 1000);
      setTimeout(function(){ x.classList.toggle("show"); }, 5000);
    </script>
  </div>
<% end %>

app/views/shared/_mapbox-itinary.html.erb
<div id='map'> </div>

<% content_for(:js) do %>
  <% javascript_pack_tag 'itinary-mapbox-direction' %>
<% end %>

app/views/shared/_mapbox.html.erb
<div id='map'> </div>

<% content_for(:js) do %>
  <% javascript_pack_tag 'choice-mapbox' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-walk">
  <div class="circle-navbar-desktop hidden-xs hidden-sm">

    <div class="navbar-walk-desktop hidden-xs hidden-sm">

       <div class="desktop-links">
        <% if user_signed_in? %>


        <div class="navbar-link">
          <%= link_to "Accueil", root_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">
          <%= link_to "Mes itinéraires", display_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "link-navbar" %>
        </div>


        <% else %>


        <div class="navbar-link">
          <%= link_to "Accueil", root_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">
          <%= link_to "Connexion", new_user_session_path, class: "link-navbar" %>
        </div>


        <div class="navbar-link">
          <%= link_to "Inscription",new_user_registration_path, class: "link-navbar" %>
        </div>



        <% end %>
      </div>

      <div class="drop-menu-desktop">
        <%= image_tag "seety_icon_inverse.png" %>
      </div>

      <div class="drop-menu-close-desktop">
        <i class="fas fa-times"></i>
      </div>

    </div>

  </div>

  <div class="circle-navbar-mobile hidden-md hidden-lg">

    <div class="navbar-walk-mobile hidden-md hidden-lg">

      <div class="mobile-links">
        <% if user_signed_in? %>


        <div class="navbar-link">
          <%= link_to "Accueil", root_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">
          <%= link_to "Mes Itinéraires", display_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "link-navbar" %>
        </div>


        <% else %>


        <div class="navbar-link">
          <%= link_to "Accueil", root_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">
          <%= link_to "Connexion", new_user_session_path, class: "link-navbar" %>
        </div>

        <div class="navbar-link">

          <%= link_to "Inscription",new_user_registration_path, class: "link-navbar" %>
        </div>



        <% end %>
      </div>

      <div class="drop-menu-mobile">
        <%= image_tag "seety_icon_inverse.png" %>
      </div>

      <div class="drop-menu-close-mobile">
        <i class="fas fa-times"></i>
      </div>

    </div>

  </div>


</div>

app/views/shared/_searchbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 container-flex">
      <i class="fas fa-search"></i>
      <div class="container-search-bar">
        <form autocomplete="off" action="/TOCOMPLETE">
          <div class="autocomplete">
            <input id="myInput" class="form-control form-control-lg" type="text" placeholder="Entrez votre ville">
          </div>
          <input class="btn btn-success" type="submit">
        </form>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_pack_tag 'cities-autocomplete' %>
<% end %>

app/views/shared/_static-mapbox.html.erb
<script type="text/javascript">
  var marker_long = 3.0565;
  var marker_lat = 50.6302;
  var marker = `pin-s-(${marker_long},${marker_lat})`;
  var staticRequest = `https://api.mapbox.com/styles/v1/mapbox/light-v9/static/${marker}/${marker_long},${marker_lat},10,0,0/300x200?access_token=pk.eyJ1IjoiaGVucmk0NSIsImEiOiJjam52bjV4anAwYjc2M3ZxdHd5NjlpbGc5In0.jNKjBZ2d3T4G7qzcmRb77A`;

  $.ajax({
    method: 'GET',
    url: staticRequest,
  }).done(function(data) {
    console.log(data);
  })


</script>
<img src='https://api.mapbox.com/styles/v1/mapbox/light-v9/static/pin-s-marker+285A98(3.0565,50.6302)/3.0565,50.6302,11,0,0/300x200?access_token=pk.eyJ1IjoiaGVucmk0NSIsImEiOiJjam52bjV4anAwYjc2M3ZxdHd5NjlpbGc5In0.jNKjBZ2d3T4G7qzcmRb77A'>