config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Vue de composant
  get "/components", to: 'cities#components', as: :components

  #racine de l'app
  root to: 'cities#home', as: :root

  post '/search', to: 'cities#search', as: :search_city # redirection avec l'id

  get '/explications/:name', to: 'cities#explications', as: :explications # Avec id de la ville

  post '/city/:city_id', to: 'itineraires#search', as: :post_city # Crée l'itinéraire avec l'id de la ville --> redirige avec id itinéraire

  get '/vos-monuments/:id', to: 'itineraires#choice', as: :choice
  # permet d'ajouter avec AJAX un monument à un itinéraire
  post '/vos-monuments/:id/:monument_id', to: 'itineraires#ajout', as: :ajout
  delete '/vos-monuments/delete/:id/:monument_id', to: 'itineraires#delete', as: :delete

  #affichage du recap
  get '/synthese/:id', to: 'itineraires#recap', as: :recap # avec id itinéraire
  #delete avec AJAX d'un monument à un itinéraire
  post '/synthese/:id/:monument_id', to: 'itineraires#supprimer', as: :supprimer

  #affichage de l'itinéraire
  get '/itineraire/:id', to: 'itineraires#show', as: :itinary # avec id itinéraire

  post '/itineraires/:id', to: 'itineraires#metrics', as: :metrics # Enregistrement des metrics de l'itinéraire

  get '/vos-itineraires', to: 'itineraires#display', as: :display #affichage des itinéraires précedent de l'utilisateur
#page mes itinéraires (par villes)

  get '/geocoder', to: 'itineraires#geocoder'

  post '/itineraire/point-depart/:id', to: 'itineraires#point_de_depart'

end

app/models/itineraire.rb
class Itineraire < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_many :intermediaires, dependent: :destroy
  has_many :monuments, through: :intermediaires
end

app/controllers/itineraires_controller.rb
class ItinerairesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:ajout]

  def search
    @city = City.find(params[:city_id])
    @itineraire = Itineraire.new(name: @city.name) # Ajout de city au modèle (ou through)
    @itineraire.city = @city
    @itineraire.user = current_user
    @itineraire.save
    redirect_to choice_path(@itineraire)
  end

  def choice
    @itineraire = Itineraire.find(params[:id])
    # pluck send a array of id
    @monuments = Monument.where(city: @itineraire.city).where.not(id: @itineraire.monuments.pluck(:id)).order(score: :desc)
    # Set the compteur to 0
    @itineraire.update(compteur: 0)
    # Make accessible to JS everything define in choice.json.rabl (in views)
    gon.itineraire = @itineraire
    gon.itineraireMonuments = @itineraire.monuments
    gon.monuments = @monuments
  end

  def ajout
    # Find the itineraire
    @itineraire = Itineraire.find(params[:id])
    # Find the monument
    @monument = Monument.find(params[:monument_id])
    # Add the monument to the itineraire
    @itineraire.monuments.push(@monument)
    # Set the compteur to the next index of the added monuments
    @itineraire.update(compteur: params["compteur"].to_i + 1)
    redirect_to choice_path(@itineraire)
  end

  def delete
    # Find the itineraire
    @itineraire = Itineraire.find(params[:id])
    # # Find the monument
    @monument = Monument.find(params[:monument_id])

    @itineraire.monuments.delete(@monument)
  end

  def recap
    @itineraire = Itineraire.find(params[:id])
    #récupérer les monuments selectionnés

    @monuments = @itineraire.monuments
    #make accessible to JS what is done in recap
    gon.monuments = @monuments
    gon.itineraire = @itineraire
  end

  # A ENLEVER
  def supprimer
    # Find the itineraire
    @itineraire = Itineraire.find(params[:id])
    # Find the monument to delete
    @monument = Monument.find(params[:monument_id])
    #delete the monument of the itinary
    @itineraire.monuments.destroy(@monument)

    #permet à la vue de gérer si l'utilisateur utilise JS ou pas
    respond_to do |format|
      format.html { redirect_to recap_path(@itineraire) }
      format.js # will render 'app/views/itineraries/supprimer.js.erb'
    end
  end

  def show
    @itineraire = Itineraire.find(params[:id])
    @monuments = @itineraire.monuments
    coord_initial = compute_array(@monuments)
    x = []
    coord_initial.each { |e| x.push(e[0].to_f) }
    y = []
    coord_initial.each { |e| y.push(e[1].to_f) }
    @coord = Voyageur.new(y, x).call
    @coord = transform(@coord)

    # Logique Point de Départ

    # Si il n'y en a pas cela ne change rien
    if @itineraire.point_depart == ""
      #coord ordonnée par le service objet
      gon.coordonees = @coord

    # Sinon ajoute pour la route seulement les coordonées
    else
      pt_depart = to_hash_point_depart(@itineraire.point_depart)
      tmp = @coord.clone
      tmp.pop
      tmp.unshift([pt_depart[:lat], pt_depart[:lng]])
      tmp.push([pt_depart[:lat], pt_depart[:lng]])
      gon.coordonees = tmp
      gon.pointDepart = pt_depart
    end

    gon.itineraire = @itineraire
    gon.monuments = @monuments #monuments NON ordonnées
    gon.idsOrdonee = refind(@coord, @monuments).map {|monument| monument[0][:id]} #Array des ID des monuments ordonénes par le service object
    gon.monumentsOrdonne = refind(@coord, @monuments)
    gon.itineraire = @itineraire#Array des monuments ordonnées par le service objet.
  end

  def display #affiche l'itinéraire final d'un ancien trajet
    @itineraires_perso = Itineraire.where(user_id: current_user.id).order(created_at: :desc).select { |itineraire| itineraire.monuments.size != 0 }
  end

  def metrics
    @itineraire = Itineraire.find(params[:id])
    @itineraire.update(duration: params["duration"])
    @itineraire.update(distance: params["distance"])
  end

  def geocoder
    Geocoder.configure(lookup: :opencagedata, api_key: ENV["OPEN_CAGE"])
    results = Geocoder.search(params[:query])
    render json: { results: results }
  end

  def point_de_depart
    @itineraire = Itineraire.find(params[:id])
    @itineraire.update(point_depart: params[:query])
  end

  private

  def compute_array(monuments)
    arr = []
    monuments.each { |monument| arr.push([monument.latitude, monument.longitude]) }
    return arr
  end

  def transform(coord)
    arr_final = []
    coord[:latitudes].size.times { |i| arr_final.push([coord[:latitudes][i], coord[:longitudes][i]]) }
    return arr_final
  end

  def refind(coords, monuments)
    arr = []
    coords.each_with_index do |coord, index|
      if index != coords.size - 1
        selec = monuments.select { |monument| monument[:longitude] == coord[0].to_s && monument[:latitude] == coord[1].to_s }
        arr.push(selec)
      end
    end
    return arr
  end

  def to_hash_point_depart(string)
    return {
      lng: string.match(/lng(\d+\.\d+)/)[1].to_f,
      lat: string.match(/lat(\d+\.\d+)/)[1].to_f,
      address: string.match(/address(.+)/)[1]
    }
  end
end

app/views/itineraires/choice.html.erb
<% content_for :title, "Seety - Choix des monuments" %>

<%= link_to explications_path(@itineraire.city.name) do %>
  <div id="return"><i class="fas fa-arrow-left"></i></div>
<% end %>

<div id="green-choice">

  <div class="green-choice-circle">
    <i class="fas fa-arrow-right"></i>
  </div>
  <div class="green-choice-container">
    <%= link_to "J'ai choisi mes monuments", recap_path(@itineraire), class: "choice-made" %>
  </div>
</div>



<div id="map"></div>

<div class="cards">

<div id="metrics-distance">

</div>


<% @monuments.each_with_index do |monument, index| %>
  <div class="card" id="monument-<%= monument.id %>" style="<%= "visibility: hidden;" unless index.zero? %>">
    <div class="monument-image-div">
      <%= cl_image_tag(monument.photo, class: "monument-image-new") %>
    </div>
    <h2 class="monument-name"><%= monument.name %></h2>

    <div class="choice-maker">
      <div class="choice-validate choice-no">
        <%= image_tag "close.svg" %>
      </div>
      <div class="choice-validate choice-yes">
        <%= image_tag "check.svg" %>
      </div>
    </div>
    <div class="card-stars">
      <% compteur_empty_stars = 5 %>
      <% score_to_stars(monument.score).to_i.times do %>
        <i class="fas fa-star"></i>
        <% compteur_empty_stars -= 1 %>
      <% end %>
      <% if (score_to_stars(monument.score) - score_to_stars(monument.score).to_i == 0.5) %>
        <i class="fas fa-star-half-alt"></i>
        <% compteur_empty_stars -= 1 %>
      <% end %>
      <% compteur_empty_stars.times do %>
      <i class="far fa-star"></i>
      <% end %>
    </div>

    <div class="card-infos" id="plus-info-<%= monument.id %>">
      <i class="fas fa-info-circle"></i>
    </div>
  </div>
<% end %>

<% @monuments.each_with_index do |monument, index| %>
  <div class="card-info" id="monument-info-<%= monument.id %>" style="<%= "visibility: hidden;" %>">
    <div class="monument-image-div-info">
      <%= cl_image_tag(monument.photo, class: "monument-image-new") %>
    </div>

    <div class="card-stars-info" id="putain-de-stars">
     <% compteur_empty_stars = 5 %>
     <% score_to_stars(monument.score).to_i.times do %>
       <i class="fas fa-star"></i>
       <% compteur_empty_stars -= 1 %>
     <% end %>
     <% if (score_to_stars(monument.score) - score_to_stars(monument.score).to_i == 0.5) %>
       <i class="fas fa-star-half-alt"></i>
       <% compteur_empty_stars -= 1 %>
     <% end %>
     <% compteur_empty_stars.times do %>
     <i class="far fa-star"></i>
     <% end %>
   </div>

    <div class="text-card-info">
      <h2 class="monument-name-info"><%= monument.name %></h2>

        <div class="info-supp">
          <% if monument.protection == "Classé MH"%>
            <h3>Classé monument historique</h3>
          <% elsif monument.protection == "Inscrit MH" %>
            <h3>Inscrit monument historique</h3>
          <% else  %>
            <h3>Monument non classé historiquement</h3>
          <% end  %>
          <h4><%= monument.address == "no address" ? "Pas d'adresse exacte disponible": monument.address %></h4>
        </div>

      <div class="description-info">
        <h3>Description</h3>
        <p><%= monument.description %></p>
      </div>

    </div>

    <div class="delete-card-info" id="delete-info-<%= monument.id %>">
      <%= image_tag "return.svg" %>
    </div>

  </div>
<% end %>
</div>

<% content_for(:js) do %>
  <%= javascript_pack_tag 'choice' %>
<% end %>


<style>
  body, html {
    overflow: hidden;
  }

  body {
    position: relative;
  }
</style>

app/views/itineraires/display.html.erb
<div class="display-container">

  <div class="container">
    <div class="row">
      <div class="scroll-fiche-city">

      <% @itineraires_perso.each do |itineraire| %>
      <% path = itinary_path(itineraire.id) if itineraire.compteur >2 %>
      <% path = choice_path(itineraire.id) if itineraire.compteur < 3 %>

      <div class="col-xs-12 col-md-6">
        <div class="fiche-city-wrapper">
          <%= link_to itinary_path(itineraire.id), class: "link-fiche-city" do%>

          <div class="fiche-city-display">
            <%= cl_image_tag(itineraire.city.photo) %>

            <div class="display-info">
              <h4 class="city-display-name"><%= itineraire.city.name %></h4>
              <h3 id="created">Créé le <%= itineraire.created_at.localtime("+01:00").strftime('%e %B %Y à %Hh%M') %></h3>

              <div class="infos-iti">
                <p id="nb-monuments">
                  <i class="fas fa-university"></i>
                  <%= itineraire.monuments.size %>
                </p>

                <p id="duration">
                   <i class="far fa-clock"></i>
                  <%= itineraire.duration %>
                </p>

                <p id="distance">
                  <i class="fas fa-walking"></i>
                  <%= itineraire.distance %>
                </p>
              </div>

            </div>

          </div>

          <%end%>
        </div>
      </div>

      <%end%>

      </div>
    </div>
  </div>

</div>

app/views/itineraires/recap.html.erb
<% content_for :title, "Seety - Validation d'itinéraire" %>

<%= link_to choice_path(@itineraire) do %>
  <div id="return"><i class="fas fa-arrow-left"></i></div>
<% end %>

<div id="green-choice">
  <div class="green-choice-circle">
    <i class="fas fa-arrow-right"></i>
  </div>
  <div class="green-choice-container">
    <a href="#" class= "choice-made" data-toggle="modal" data-target="#departModal">Calculer mon parcours</a>
  </div>
</div>

<div id="map"></div>


<div class="cards-recap">

  <% @monuments.each_with_index do |monument, index| %>
  <div class="card-recap" id="monument-<%= monument.id %>">
    <div class="monument-image-div-recap">
      <%= cl_image_tag(monument.photo, class: "monument-image-new-recap") %>
    </div>
    <h2 class="monument-name-recap"><%= monument.name %></h2>

    <div class="card-stars-recap">
      <% compteur_empty_stars = 5 %>
      <% score_to_stars(monument.score).to_i.times do %>
        <i class="fas fa-star"></i>
        <% compteur_empty_stars -= 1 %>
      <% end %>
      <% if (score_to_stars(monument.score) - score_to_stars(monument.score).to_i == 0.5) %>
        <i class="fas fa-star-half-alt"></i>
        <% compteur_empty_stars -= 1 %>
      <% end %>
      <% compteur_empty_stars.times do %>
      <i class="far fa-star"></i>
      <% end %>
    </div>

      <div class="delete-card" id="delete-id-<%= monument.id %>">
        <i class="fas fa-times"></i>
      </div>
  </div>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="departModal" tabindex="-1" role="dialog" aria-labelledby="departModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-pt-depart">
      <div class="modal-header text-center modal-pt-header">
        <h5 class="modal-title" id="departModalLabel">Voulez-vous ajouter un point de départ ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span id="close-modal" aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-pt-body">


        <form class="form-container modal-form" action="/">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="autocomplete auto-modal">
            <div class="form-group">
              <input type="text" name="name" placeholder="Point de départ" id="myInput" class="form-control">
            </div>
            <button type="submit" name="button" class="button-icon"><i class="fas fa-search"></i></button>
          </div>
        </form>

        <div id="container-geocode">

        </div>
      </div>
      <div class="modal-footer modal-pt-footer">
        <%= link_to "Pas de point de départ", itinary_path(@itineraire), id: "noPointDepart", class: "text-center" %>
        <a href="#" id="displayGeocoder" class="text-center">Je veux rentrer mon point de départ</a>
        <%= link_to "J'ajoute mon point de départ", itinary_path(@itineraire), id: "addPointDepart", class: "text-center" %>
      </div>
    </div>
  </div>
</div>


<% content_for(:js) do %>
  <%= javascript_pack_tag 'recap' %>
<% end %>


<style>
  body, html {
    overflow: hidden;
  }

  body {
    position: relative;
  }
</style>

app/views/itineraires/show.html.erb
<% content_for :title, "Seety - Itinéraire Final" %>

<div id="export">
  Google Maps
</div>
<%= link_to recap_path(@itineraire) do %>
  <div id="return"><i class="fas fa-arrow-left"></i></div>
<% end %>


<div id="center-perso">
  <i class="fas fa-street-view"></i>
</div>

<div id="no-geoloc" class="text-center">
  <p>Pour avoir accès à votre position, activez les données de localisation de votre navigateur.</p>
</div>


<div id='map-final'>
  <div id="metrics-distance">
  </div>

<div class="cards">


  <div class="container-minirecaps">
    <% @monuments.each do |monument| %>
    <div class="container-minirecap" id="<%= monument.id %>">
      <h5><%= monument.name %></h5>
      <i class="fas fa-chevron-circle-up" id="open-id-<%= monument.id %>"></i>
    </div>
    <% end %>
  </div>


  <% @monuments.each_with_index do |monument, index| %>
    <div class="card" id="monument-<%= monument.id %>" style="<%= "visibility: hidden;" %>">
      <div class="monument-image-div">

        <%= cl_image_tag(monument.photo, class: "monument-image-new") %>
      </div>
      <h2 class="monument-name"><%= monument.name %></h2>

      <div class="card-stars">
      <% compteur_empty_stars = 5 %>
      <% score_to_stars(monument.score).to_i.times do %>
        <i class="fas fa-star"></i>
        <% compteur_empty_stars -= 1 %>
      <% end %>
      <% if (score_to_stars(monument.score) - score_to_stars(monument.score).to_i == 0.5) %>
        <i class="fas fa-star-half-alt"></i>
        <% compteur_empty_stars -= 1 %>
      <% end %>
      <% compteur_empty_stars.times do %>
      <i class="far fa-star"></i>
      <% end %>
      </div>

      <div class="card-infos" id="plus-info-<%= monument.id %>">
        <i class="fas fa-info-circle"></i>
      </div>

      <div class="delete-card" id="close-info-<%= monument.id %>">
        <%= image_tag "return.svg", style: "color: #CBCBCB; width: 32px; height: 32px;" %>
      </div>
    </div>
  <% end %>

  <% @monuments.each_with_index do |monument, index| %>
    <div class="card-info" id="monument-info-<%= monument.id %>" style="<%= "visibility: hidden;" %>">
      <div class="monument-image-div-info">
        <%= cl_image_tag(monument.photo, class: "monument-image-new") %>
      </div>

      <div class="top-card-info">
        <div class="delete-card-info" id="delete-info-<%= monument.id %>">
          <%= image_tag "return.svg" %>
        </div>

        <div class="card-stars-infos" id="putain-de-stars">
        <% compteur_empty_stars = 5 %>
        <% score_to_stars(monument.score).to_i.times do %>
          <i class="fas fa-star"></i>
          <% compteur_empty_stars -= 1 %>
        <% end %>
        <% if (score_to_stars(monument.score) - score_to_stars(monument.score).to_i == 0.5) %>
          <i class="fas fa-star-half-alt"></i>
          <% compteur_empty_stars -= 1 %>
        <% end %>
        <% compteur_empty_stars.times do %>
        <i class="far fa-star"></i>
        <% end %>
      </div>
    </div>

    <div class="text-card-info">
      <h2 class="monument-name-info"><%= monument.name %></h2>

        <div class="info-supp">
          <% if monument.protection == "Classé MH"%>
            <h3>Classé monument historique</h3>
          <% elsif monument.protection == "Inscrit MH" %>
            <h3>Inscrit monument historique</h3>
          <% else  %>
            <h3>Monument non classé historiquement</h3>
          <% end  %>
          <h4><%= monument.address == "no address" ? "Pas d'adresse exacte disponible": monument.address %></h4>
        </div>

      <div class="description-info">
        <h3>Description</h3>
        <p><%= monument.description %></p>
      </div>

    </div>


    </div>
  <% end %>
</div>

<% content_for(:js) do %>
  <% capture do %>
    <% concat(javascript_pack_tag 'itinary-mapbox-direction') %>
    <% concat(javascript_pack_tag 'show') %>
  <% end %>
<% end %>



<style>
  body, html {
    overflow: hidden;
  }

  body {
    position: relative;
  }
</style>

app/views/itineraires/supprimer.js.erb
document.querySelector("[card-id='<%= @monument.id %>']")
  .remove();