config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Vue de composant
  get "/components", to: 'cities#components', as: :components

  #racine de l'app
  root to: 'cities#home', as: :root

  post '/search', to: 'cities#search', as: :search_city # redirection avec l'id

  get '/explications/:name', to: 'cities#explications', as: :explications # Avec id de la ville

  post '/city/:city_id', to: 'itineraires#search', as: :post_city # Crée l'itinéraire avec l'id de la ville --> redirige avec id itinéraire

  get '/vos-monuments/:id', to: 'itineraires#choice', as: :choice
  # permet d'ajouter avec AJAX un monument à un itinéraire
  post '/vos-monuments/:id/:monument_id', to: 'itineraires#ajout', as: :ajout
  delete '/vos-monuments/delete/:id/:monument_id', to: 'itineraires#delete', as: :delete

  #affichage du recap
  get '/synthese/:id', to: 'itineraires#recap', as: :recap # avec id itinéraire
  #delete avec AJAX d'un monument à un itinéraire
  post '/synthese/:id/:monument_id', to: 'itineraires#supprimer', as: :supprimer

  #affichage de l'itinéraire
  get '/itineraire/:id', to: 'itineraires#show', as: :itinary # avec id itinéraire

  post '/itineraires/:id', to: 'itineraires#metrics', as: :metrics # Enregistrement des metrics de l'itinéraire

  get '/vos-itineraires', to: 'itineraires#display', as: :display #affichage des itinéraires précedent de l'utilisateur
#page mes itinéraires (par villes)

  get '/geocoder', to: 'itineraires#geocoder'

  post '/itineraire/point-depart/:id', to: 'itineraires#point_de_depart'

end

app/models/city.rb
class City < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  validates :name, uniqueness: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :components]

  def components
    @monuments = Monument.where(city: "1")
    gon.monuments = @monuments
  end

  def home
    @cities = City.all
    gon.cities = @cities

    render layout: "layout_home"
  end

  def search
    redirect_to explications_path(params[:name])
  end

  def explications
    # Sélectionne la ville pour pouvoir afficher son nom
    @city = City.where(name: params[:name]).first
    gon.city = @city
  end
end

app/views/cities/components.html.erb
<div class="display-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-2">
      <% @itineraires_perso.each do |itineraire| %>
      <% path = itinary_path(itineraire.id) if itineraire.compteur >2 %>
      <% path = choice_path(itineraire.id) if itineraire.compteur < 3 %>

        <div class="fiche-city-wrapper">
      <%= link_to itinary_path(itineraire.id), class: "link-fiche-city" do %>
          <div class="fiche-city-display">
            <%= cl_image_tag(itineraire.city.photo) %>
            <%= itineraire.duration %>
            <%= itineraire.distance %>
            <%= itineraire.created_at %>
            <%= itineraire.monuments.size %>
            <div class="city-description">
              <h3><%= itineraire.city.name %></h3>


            </div>
          </div>
        </div>
        <%end%>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/cities/explications.html.erb
<% content_for :title, "Seety - Explications" %>


<div class="page-explications">


  <div id="map-explics">

  </div>


  <div class="placement">
    <!-- <span class="banner-typed-text"></span> Je n'arrive pas à mettre du CSS dessus....-->

    <div class="encart">
      <div class="bouton-explics">
        <div class="fake-choice-maker">
          <div class="fake-choice-validate choice-no">
          <%= image_tag "close.svg" %>
          </div>
          <div class="fake-choice-validate choice-yes">
          <%= image_tag "check.svg" %>
          </div>
        </div>
      </div>
      <div class="text-explics">
      <p> Je like les monuments qui m'intéressent à <%= @city.name %>.</p>
      </div>
    </div>

    <div class="encart">
      <div class="bouton-explics">
          <div class="bouton-vert">
          <i class="fas fa-arrow-right"></i>
          </div>
      </div>
      <div class="text-explics">
        <p> Je valide les monuments que je veux visiter lors de mon exploration de la ville.</p>
      </div>
    </div>

    <div class="encart">
      <div class="bouton-explics">
        <div class="bouton-explics">
          <%= image_tag("seety_icon_inverse.png", alt: "logok", id: "logo") %>
        </div>
        </div>
        <div class="text-explics">
        <p> Je me laisse guider par seety qui va calculer pour moi l'itinéraire optimal.</p>
      </div>
    </div>
  </div>

  <div class="choice">
    <div class="choice-container">
      <%= link_to "J'ai compris !", post_city_path(@city), method: :post %>
    </div>
  </div>


</div>


<% content_for(:js) do %>
  <%= javascript_pack_tag 'explications' %>
<% end %>

app/views/cities/home.html.erb
<% content_for :title, "Seety - Page d'Accueil" %>

<div class="home-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <div class="home-description">
          <h1 class="text-center">SEETY</h1>
          <p class="text-center">
            <span class="banner-typed-text"></span>
          </p>

          <div class="container-flex">

            <form class="form-container" action="<%= search_city_path %>" method="post">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              <div class="autocomplete">
                <div class="form-group">
                  <input type="text" name="name" placeholder="Entrez votre ville" id="myInput" class="form-control">
                </div>
                <button type="submit" name="button" class="button-icon"><i class="fas fa-search"></i></button>
              </div>
            </form>


          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="city-home-wrapper">
  <div class="available-cities">
    <h1>Les villes visitées par nos seetyseurs c'est ici:</h1>
  </div>

<div class="container-fiche-city">
  <% @cities.each do |city| %>
    <%= link_to explications_path(city.name), class: "link-fiche-city" do %>
      <div class="fiche-city">
        <%= cl_image_tag(city.photo) %>
        <div class="city-description">
          <h3><%= city.name %></h3>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
</div>

<div class="presentation-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="home-presentation">
          <p>
            <br>Tu n'as qu'une journée pour visiter une ville ? Mais que faire ?</br>
            <br>Seety est là pour toi.</br>
            <br>Choisis une ville, ensuite nous prenons tout en main. Grâce à notre algorithme nous te proposons les meilleurs monuments à visiter. Tu sélectionnes ceux qui t'intéressent et hop c'est parti! Seety te calcule un itinéraire optimisé.</br>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_pack_tag 'cities-autocomplete' %>
  <%= javascript_pack_tag 'home' %>
<% end %>